#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# (c) ACE 

import os

class Config(object):
    # get a token from @BotFather
    pass
    """
    BOT_TOKEN = os.environ.get("BOT_TOKEN", "7252938527:AAGkslGBnXthvmRsP6N0V8CZW0xWQ2WzhMc")
    API_ID = int(os.environ["API_ID", 29640188]
    API_HASH = os.environ["API_HASH", "e470abc84a3bc445997ee4ea5be87deb"]
    AUTH_USERS = "7504263874,6886826162 """
# jisko bhi is repo ko deploy karne me error aa raha ho ( https://t.me/Stubborn1223 ) ye mere TG ka id ha message karke iska screen shot send kar dena me error solve kar dunga. 
